Project->Sentiment Analysis

Project Goal->Classify movie reviews as positive, negative, or sometimes neutral based on the review text.

To build the model using the ml,
There are the following the step ->
1.import the require library
2. DataSet->to collect the dataset using Kaggle and imdb
3.Preprocessing-> 1.convert the lower case
                  2.remove the punctuation and html tag and stopword
                  3.to apply the Tokenization
                  4.Stemming and Lemmatization
                  5.Handle the negations
4.Split the data
5.Feature Extraction-> (to convert the text into the number) using the techinque
                      like bow,tf-idf,word embedding etc..
6. model building-> to train the model using the ml algorithmslike (navie
                       bayes,random forest,Logistic regression etc..)
7.model Evaluation
8.Hyperparameter tunning -> using grid search cv and Random search cv
9.Save the model
10.build the website usng the Flask,HTML,CSS etc..
11. to deploy the project the cloud like "Render".

1.import the require **library**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib  # Import the top-level matplotlib module

print(np.__version__)
print(pd.__version__)
print(sns.__version__)
print(matplotlib.__version__)  # Now you can access matplotlib.__version__

2.0.2
2.2.2
0.13.2
3.10.0


In [ ]:
df = pd.read_csv("IMDB Dataset.csv", on_bad_lines='skip', engine='python')

In [ ]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
# shape of the data
df.shape

(1613, 2)

In [ ]:
# column name of the data
df.columns

Index(['review', 'sentiment'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1613 entries, 0 to 1612
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     1613 non-null   object
 1   sentiment  1613 non-null   object
dtypes: object(2)
memory usage: 25.3+ KB


In [ ]:
# count the unique value of the dataset


In [ ]:
df['sentiment'].value_counts()

sentiment
positive    820
negative    793
Name: count, dtype: int64

the datset is balanced as there are equal number of datapoint in negative and positive sentiments.

In [ ]:
df.sample(5)

review sentiment
855   A friend lent me this DVD, which he got from t...  positive
1299  The first hour or so of the movie was mostly b...  positive
166   Originally I was a Tenacious D fan of their fi...  positive
873   It is always difficult to bring a 450 pages bo...  positive
974   Whatever rating I give BOOM is only because of...  negative

In [ ]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [ ]:
# find the duplicated value
df.duplicated().sum()

np.int64(0)

In [ ]:
# drop  the duplicated value
df = df.drop_duplicates(keep='first')

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.shape

(1613, 2)

3.Processing the data(text preprocessing])

1.all data convert to the lower case

In [ ]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
import nltk
nltk.download('punkt')  # This is already in your code
nltk.download('stopwords')  # This is also in your code
nltk.download('averaged_perceptron_tagger')  # For proper tokenization


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [ ]:
# 1.Lower case
def textloew(text):
    text=text.lower()
    return text

In [ ]:
df['review']=df['review'].apply(textloew)

In [ ]:
df.head()

review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

2.remove the html tags

In [ ]:
import re

def removehtmltags(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)


In [ ]:
df['review']=df['review'].apply(removehtmltags)

In [ ]:
df.head()

review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

3. Remove the punctation in dataset

In [ ]:
import string

In [ ]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
ex=string.punctuation

In [ ]:
def remove_pun(text):
    return text.translate(str.maketrans(" "," ",ex))

In [ ]:
df['review']=df['review'].apply(remove_pun)

In [ ]:
df.head()

review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production the filming tech...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

4.Remove Stop Word

remove stopword-some common word that are present in the text but do not contribute in meaning of sentence

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Download necessary resources
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab') # Download the missing 'punkt_tab' resource

def remove_stopwords(text):
    # Set of English stop words
    stop_words = set(stopwords.words('english'))

    # Tokenize the input text
    words = word_tokenize(text)

    # Filter out stop words
    filtered_words = [word for word in words if word.lower() not in stop_words]

    # Return filtered words (can also return as string if needed)
    return filtered_words

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


In [ ]:
df['review']=df['review'].apply(remove_stopwords)

In [ ]:
df.head()

review sentiment
0  [one, reviewers, mentioned, watching, 1, oz, e...  positive
1  [wonderful, little, production, filming, techn...  positive
2  [thought, wonderful, way, spend, time, hot, su...  positive
3  [basically, theres, family, little, boy, jake,...  negative
4  [petter, matteis, love, time, money, visually,...  positive

5. **Stemming**

Stemming is a process in Natural Language Processing (NLP) where words are reduced to their root form (or stem), typically by removing suffixes or prefixes.

In [ ]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

In [ ]:
def porter_stemming(words):
    return [stemmer.stem(word) for word in words]


In [ ]:
df['review']=df['review'].apply(porter_stemming)

In [ ]:
df.head()

review sentiment
0  [one, review, mention, watch, 1, oz, episod, y...  positive
1  [wonder, littl, product, film, techniqu, unass...  positive
2  [thought, wonder, way, spend, time, hot, summe...  positive
3  [basic, there, famili, littl, boy, jake, think...  negative
4  [petter, mattei, love, time, money, visual, st...  positive

Label **Encoder**

A Label Encoder is a preprocessing tool in machine learning used to convert categorical (text) labels into numeric form so they can be used by ML models

In [ ]:
# then the apply the label encoder then target column is converted in numerical because machine learning algorithem work on numerical data
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df['sentiment']=lb.fit_transform(df['sentiment'])

In [ ]:
df.head()

review  sentiment
0  [one, review, mention, watch, 1, oz, episod, y...          1
1  [wonder, littl, product, film, techniqu, unass...          1
2  [thought, wonder, way, spend, time, hot, summe...          1
3  [basic, there, famili, littl, boy, jake, think...          0
4  [petter, mattei, love, time, money, visual, st...          1

In [ ]:
df['sentiment'].value_counts()

sentiment
1    820
0    793
Name: count, dtype: int64

Feature Engg.(Text vecterizer)

A Text Vectorizer is a tool used in Natural Language Processing (NLP) to convert text data into numerical format so machine learning models can understand and process i

using TF-IDF

TF-IDF stands for Term Frequency–Inverse Document Frequency. It's a text vectorization technique used to convert text into meaningful numerical vectors.

It measures how important a word is in a document relative to a collection of documents (corpus).

Formula Breakdown:
TF (Term Frequency):
How frequently a word appears in a document.

javascript
Copy code
TF = (Number of times term t appears in a document) / (Total terms in the document)
IDF (Inverse Document Frequency):
How rare the word is across all documents.

ini
Copy code
IDF = log_e(Total number of documents / Number of documents containing the term)
TF-IDF = TF × IDF



In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    ngram_range=(1, 2),     # Use unigrams + bigrams
    min_df=2,               # Ignore rare terms
    max_df=0.9,             # Ignore too common terms
    stop_words='english',
    sublinear_tf=True       # Apply sublinear term frequency scaling
)
# Replace 'text_train' with 'df['review']' to use the 'review' column
x = vectorizer.fit_transform(df['review']).toarray()

In [ ]:
# from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
# cv = CountVectorizer()
# tfidf = TfidfVectorizer(max_features=3000)
# df['review'] = df['review'].apply(lambda words: " ".join(words))

In [ ]:
# x = tfidf.fit_transform(df['review']).toarray()

In [ ]:
y = df['sentiment'].values # Assign to a new variable 'y'

Split the dataset train and test

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
y_train

array([0, 1, 1, ..., 1, 0, 0])

In [ ]:
x_train.shape

(1290, 19442)

In [ ]:
x_test.shape

(323, 19442)

5.6.model building/model evaluation

to train the model using the ml algorithmslike (navie
                       bayes,random forest,Logistic regression etc..)

#  using the algorithem
classification
1. Naive Bayes-> GaussianNB,MultinomialNB,BernoulliNB
2.logistic reg.
3.decision tree
4. random forest classifier
5. knn
6.Adaboost classifier
then improve your performence using Ensemble technique like
7.bagging classifeier
8.boosting classifer
9.voting classifier
10.svc

  #  And Evaluate the model using the
use classification metrics like
1. accuracy
2.precision
3. confusion metrics

In [ ]:
from sklearn.naive_bayes import BernoulliNB,MultinomialNB,GaussianNB
bnb=BernoulliNB()
mnb=MultinomialNB()
gnb=GaussianNB()

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score

In [ ]:
# MultinomialNB
mnb.fit(x_train,y_train)
y_pred = mnb.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(precision_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.848297213622291
0.8606060606060606
[[132  23]
 [ 26 142]]


In [ ]:
# GaussianNB
gnb.fit(x_train,y_train)
y_pred1 = gnb.predict(x_test)
print(accuracy_score(y_test,y_pred1))
print(precision_score(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1))

0.7089783281733746
0.7371794871794872
[[114  41]
 [ 53 115]]


In [ ]:
# BernoulliNB
bnb.fit(x_train,y_train)
y_pred2 = bnb.predict(x_test)
print(accuracy_score(y_test,y_pred2))
print(precision_score(y_test,y_pred2))
print(confusion_matrix(y_test,y_pred2))

0.8421052631578947
0.8588957055214724
[[132  23]
 [ 28 140]]


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
svc = SVC(kernel='sigmoid', gamma=1.0)
knc = KNeighborsClassifier()
mnb = MultinomialNB()
dtc = DecisionTreeClassifier(max_depth=5)
lrc = LogisticRegression()
rfc = RandomForestClassifier(n_estimators=50, random_state=2)
abc = AdaBoostClassifier(n_estimators=50, random_state=2)
bc = BaggingClassifier(n_estimators=50, random_state=2)
gbdt = GradientBoostingClassifier(n_estimators=50,random_state=2)

In [ ]:
# KNN
knc.fit(x_train,y_train)
y_predw = knc.predict(x_test)
print(accuracy_score(y_test,y_predw))
print(precision_score(y_test,y_predw))
print(confusion_matrix(y_test,y_predw))

0.6934984520123839
0.7315436241610739
[[115  40]
 [ 59 109]]


In [ ]:
# SVC
svc.fit(x_train,y_train)
y_predr = svc.predict(x_test)
print(accuracy_score(y_test,y_predr))
print(precision_score(y_test,y_predr))
print(confusion_matrix(y_test,y_predr))

0.8297213622291022
0.8228571428571428
[[124  31]
 [ 24 144]]


In [ ]:
# Logistic Regression
lrc.fit(x_train,y_train)
y_pred4 = lrc.predict(x_test)
print(accuracy_score(y_test,y_pred4))
print(precision_score(y_test,y_pred4))
print(confusion_matrix(y_test,y_pred4))

0.8575851393188855
0.8588235294117647
[[131  24]
 [ 22 146]]


In [ ]:
# gradient boosting decion treee
gbdt.fit(x_train,y_train)
y_predt = gbdt.predict(x_test)
print(accuracy_score(y_test,y_predt))
print(precision_score(y_test,y_predt))
print(confusion_matrix(y_test,y_predt))

0.7894736842105263
0.7688172043010753
[[112  43]
 [ 25 143]]


In [ ]:
# Decision tree classifier
dtc.fit(x_train,y_train)
y_pred5 = dtc.predict(x_test)
print(accuracy_score(y_test,y_pred5))
print(precision_score(y_test,y_pred5))
print(confusion_matrix(y_test,y_pred5))

0.7027863777089783
0.6565217391304348
[[ 76  79]
 [ 17 151]]


In [ ]:
# ensemble technique-bagging classifier
bc.fit(x_train,y_train)
y_pred8 = bc.predict(x_test)
print(accuracy_score(y_test,y_pred8))
print(precision_score(y_test,y_pred8))
print(confusion_matrix(y_test,y_pred8))

0.7554179566563467
0.7486033519553073
[[110  45]
 [ 34 134]]


In [ ]:
# Adaboost classifier
abc.fit(x_train,y_train)
y_pred6 = abc.predict(x_test)
print(accuracy_score(y_test,y_pred6))
print(precision_score(y_test,y_pred6))
print(confusion_matrix(y_test,y_pred6))

0.7956656346749226
0.7628865979381443
[[109  46]
 [ 20 148]]


In [ ]:
# Random forest classifier
rfc.fit(x_train,y_train)
y_pred4 = rfc.predict(x_test)
print(accuracy_score(y_test,y_pred4))
print(precision_score(y_test,y_pred4))
print(confusion_matrix(y_test,y_pred4))

0.8297213622291022
0.8466257668711656
[[130  25]
 [ 30 138]]


Hyperparameter tunning

Hyperparameter tuning is the process of selecting the optimal set of hyperparameters for a machine learning model. Hyperparameters are values set before the learning process begins and control how the model is trained. These can significantly affect the model’s performance.

hyperparameter tuning using Grid Search cv

Grid Search CV (Cross-Validation) is a technique used for hyperparameter tuning by performing an exhaustive search over a specified hyperparameter grid. It evaluates model performance for each combination of hyperparameters and selects the best set based on cross-validation results.

Notes:
Cross-validation is crucial because it gives a better estimate of how your model will perform on unseen data.

Parallelization (n_jobs=-1) speeds up the search process by utilizing all CPU cores.

Be cautious about the search space. A large number of hyperparameters with a large range of values will significantly increase the time it takes to perform Grid Search.

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],
    'penalty': ['l2'],
    'solver': ['liblinear'],
    'class_weight': [None, 'balanced'],
    'max_iter': [100, 200, 500]
}

In [ ]:
log_reg = LogisticRegression()
grid = GridSearchCV(log_reg, param_grid, cv=5, scoring='accuracy')

In [ ]:
grid_search.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [0.01, 0.1, 1, 10], 'max_iter': [100, 200],
                         'penalty': ['l2'], 'solver': ['liblinear']},
             scoring='accuracy')

In [ ]:
print("Best parameters:", grid_search.best_params_)
# print("Best cross-validation score:", grid_search.best_score_)

Best parameters: {'C': 10, 'max_iter': 100, 'penalty': 'l2', 'solver': 'liblinear'}


In [ ]:
# print("Best parameters:", grid_search.best_params_)
print("Best cross-validation score:", grid_search.best_score_)

Best cross-validation score: 0.8410852713178294


In [ ]:
lr=LogisticRegression(C=1,max_iter=100,penalty='l2',solver='liblinear')

In [ ]:
lr.fit(x_train,y_train)

LogisticRegression(C=1, solver='liblinear')

In [ ]:
y_prede=lr.predict(x_test)
accuracy_score(y_test,y_prede)
print(precision_score(y_test,y_prede))
print(confusion_matrix(y_test,y_prede))

0.8654970760233918
[[132  23]
 [ 20 148]]


In [ ]:
from sklearn.ensemble import VotingClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

logreg = LogisticRegression(C=1)
svm = SVC(probability=True)
rf = RandomForestClassifier()

voting = VotingClassifier(
    estimators=[('lr', logreg), ('svc', svm), ('rf', rf)],
    voting='soft'
).
voting.fit(x_train, y_train) # Change X_train_tfidf to x_train

VotingClassifier(estimators=[('lr', LogisticRegression(C=1)),
                             ('svc', SVC(probability=True)),
                             ('rf', RandomForestClassifier())],
                 voting='soft')

In [ ]:

y_pred = voting.predict(x_test)
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))


0.8606811145510835
0.8682634730538922
[[133  22]
 [ 23 145]]


To save the model in logistic regression and tfidf vecti.

In [ ]:
import pickle

In [ ]:
pickle.dump(vectorizer,open('vectorizer.pkl','wb'))
pickle.dump(lr,open('model.pkl','wb'))